import type { Metadata, Viewport } from "next";
import { Instrument_Serif, Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { SITE_URL, SITE_NAME } from "./lib/site";

const serif = Instrument_Serif({
  variable: "--font-serif",
  weight: "400",
  style: ["normal", "italic"],
  subsets: ["latin"],
});

const sans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const mono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: "#efeae0",
};

// Canonical description: ~155 characters, the upper bound Google reliably
// shows in result snippets. Front-loads the keywords (mathematician, data
// scientist, refinement schemes, machine learning) and ends with a clear
// call to action so the snippet reads as a bio, not a tagline.
const DESCRIPTION =
  "Uri Itai, Ph.D. — a mathematician and senior data scientist translating refinement schemes, geometry, and statistics into machines that learn. Tel Aviv ↔ Guangdong. Available for consulting and conversation.";

// Slightly punchier OG title — social previews give us less room than the
// browser tab, so we drop the appositive and lean on the studio voice.
const OG_TITLE = "Uri Itai, Ph.D. — Mathematician at work";

export const metadata: Metadata = {
  // metadataBase makes every other URL field below safe to write as a
  // relative path. Without it, `/opengraph-image` would log a build
  // warning and fall back to a localhost prefix.
  metadataBase: new URL(SITE_URL),

  // The title template lets sub-pages set their own title and have it
  // composed against the site name automatically. Today there's only the
  // root page, so we use `default`; tomorrow `about/page.tsx` could just
  // export `title: 'About'` and get "About — Uri Itai, Ph.D." for free.
  title: {
    default: "Uri Itai, Ph.D. — Mathematician at work",
    template: "%s — Uri Itai, Ph.D.",
  },

  description: DESCRIPTION,

  // Keywords are no longer a strong ranking signal for Google, but they
  // still inform Bing, DuckDuckGo, and some research-paper indexers. The
  // shape here mirrors how Uri actually describes his work.
  keywords: [
    "Uri Itai",
    "Uri Itai PhD",
    "mathematician",
    "data scientist",
    "Israel",
    "Tel Aviv",
    "Technion",
    "GTIIT",
    "Guangdong",
    "applied mathematics",
    "refinement schemes",
    "subdivision schemes",
    "geometric neural networks",
    "anomaly detection",
    "convex hull",
    "trustworthy AI",
    "machine learning",
    "consulting",
    "advisory",
    "lecturer",
  ],

  authors: [{ name: "Uri Itai", url: SITE_URL }],
  creator: "Uri Itai",
  publisher: "Uri Itai",

  // Stops the address bar from showing phone-call link styling on
  // numerals that look like Israeli phone numbers (e.g. years, addresses).
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },

  // Canonical URL — guards against duplicate-content penalties when the
  // site is reached via tracking-tagged links (`?utm=…`), `www.`, or
  // staging hostnames.
  alternates: {
    canonical: "/",
  },

  openGraph: {
    title: OG_TITLE,
    description: DESCRIPTION,
    url: SITE_URL,
    siteName: SITE_NAME,
    locale: "en_US",
    // `profile` is the OG type for a person; LinkedIn renders it slightly
    // differently from `website`, surfacing the name as a person card.
    type: "profile",
    // Open Graph image is generated by app/opengraph-image.tsx — Next.js
    // wires the URL automatically, but we keep the explicit reference
    // here so it's discoverable in the source.
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: "Uri Itai, Ph.D. — Mathematician at work. The 4-point interpolatory subdivision curve from his doctoral work, drawn live.",
        type: "image/png",
      },
    ],
  },

  twitter: {
    card: "summary_large_image",
    title: OG_TITLE,
    description: DESCRIPTION,
    images: ["/twitter-image"],
  },

  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  // Apple-specific — when added to home screen on iOS, sets the title
  // shown under the icon and tells iOS this is a "web app" so the
  // status-bar tint matches the paper palette.
  appleWebApp: {
    title: SITE_NAME,
    statusBarStyle: "default",
    capable: true,
  },

  category: "portfolio",
};

// JSON-LD Person schema — what gives Google enough structured signal to
// build a Knowledge Panel for the name "Uri Itai" (the boxed bio that
// can appear in the right-hand rail of search results). It's the single
// largest SEO lever for a personal site, and it stays in sync with the
// Metadata object above.
const personJsonLd = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: "Uri Itai",
  honorificSuffix: "Ph.D.",
  url: SITE_URL,
  image: `${SITE_URL}/opengraph-image`,
  jobTitle: "Senior Data Scientist · Mathematician",
  description: DESCRIPTION,
  email: "mailto:hello@uriitai.com",
  knowsLanguage: ["en", "he"],
  alumniOf: [
    {
      "@type": "CollegeOrUniversity",
      name: "Technion — Israel Institute of Technology",
      sameAs: "https://www.technion.ac.il/",
    },
  ],
  worksFor: [
    {
      "@type": "Organization",
      name: "Fetcherr",
      sameAs: "https://www.fetcherr.io/",
    },
    {
      "@type": "CollegeOrUniversity",
      name: "GTIIT — Guangdong Technion Israel Institute of Technology",
      sameAs: "https://www.gtiit.edu.cn/",
    },
    {
      "@type": "CollegeOrUniversity",
      name: "Holon Institute of Technology",
      sameAs: "https://www.hit.ac.il/",
    },
  ],
  knowsAbout: [
    "Applied mathematics",
    "Subdivision schemes",
    "Refinement schemes",
    "Geometric neural networks",
    "Anomaly detection",
    "Convex hull volume",
    "Statistical research",
    "Trustworthy AI",
    "Machine learning",
  ],
  sameAs: [
    "https://www.linkedin.com/in/uri-itai-43106316/",
    "https://medium.com/@uriitai",
  ],
};

const websiteJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: SITE_NAME,
  url: SITE_URL,
  description: DESCRIPTION,
  inLanguage: "en",
  author: {
    "@type": "Person",
    name: "Uri Itai",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${serif.variable} ${sans.variable} ${mono.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-paper text-ink selection:bg-ink selection:text-paper">
        {children}

        {/*
          JSON-LD lives in <body>, not <head>, by current schema.org +
          Google guidance: it's content describing the page, and putting
          it in the body lets Next.js cache it as part of the HTML stream
          without paying a head-render cost.

          Two separate scripts (Person + WebSite) is the canonical shape;
          combining into a graph adds a dependency on `@graph` parsing
          that not every crawler handles.
        */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(personJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
        />
      </body>
    </html>
  );
}
